direct/urls.py
from django.urls import path
from .views import share_post_direct,direct,get_messages
app_name = "direct"
urlpatterns = [
    path("share",share_post_direct,name="sharepost"),
    path("direct",direct,name="direct"),
    path("get-messages",get_messages,name="getmessages"),
    
]

instagram/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home,new_messages
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home,name="home"),
    path("",include("post.urls",namespace="post")),
    path("direct/",include("direct.urls",namespace="direct")),
    path("new-messages",new_messages,name="newmessages"),
    path("",include("account.urls",namespace="account"))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import like_post,save_post,get_users_to_share_post,get_picture_by_username,get_user_by_id, set_comment,get_comments_by_post_id
app_name = "post"
urlpatterns = [
    path("like-post",like_post,name="like-post"),
    path("save-post",save_post,name="save-post"),
    path("share-post-user",get_users_to_share_post,name="sharepostuser"),
    path("usernamepicture/<str:username>/",get_picture_by_username,name="getpicturebyusername"),
    path("set-comment/<str:text>/<str:postid>/<int:header>",set_comment,name="setcomment"),
    path("comments/<str:postid>",get_comments_by_post_id,name="getcommentsbypostid"),
    path("user/<int:id>",get_user_by_id,name="getuserbyid"),

]

templates/shared/FooterRefrence.html
{% load static %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/iziToast.min.js' %}"></script>
<script src="{% static 'js/code.js' %}"></script>

templates/shared/Header.html
{% load static %}
<header>
    <div class="container mt-4">
        <div class="row">
            <div class="col-6 col-md-3 col-lg-4 col-xl-4 text-center">
                <!-- Logo -->
                <div class="mt-2">
                    <a href="">
                        <img src="{% static 'img/logo.png' %}" alt="logo" class="logo mx-auto img-fluid">
                    </a>
                </div>
            </div>
            <div class="col-12 d-none d-md-block col-md-4 col-lg-4 col-xl-4">
                <input type="text" name="" id="" class="form-control w-100" placeholder="جستجو کنید ...">
            </div>
            <div class="col-6 col-md-5 col-lg-4 col-xl-4">
                <div class="tools mt-1">
                    <a href="" class="text-decoration-none text-dark me-3">
                        <!-- Home -->
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                            class="bi bi-house-door-fill" viewBox="0 0 16 16">
                            <path
                                d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z" />
                        </svg>
                    </a>
                    <a href="{% url 'direct:direct' %}" class="text-decoration-none text-dark me-3">
                        <!-- Direct -->
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                            class="bi bi-send-fill" viewBox="0 0 16 16">
                            <path
                                d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855H.766l-.452.18a.5.5 0 0 0-.082.887l.41.26.001.002 4.995 3.178 3.178 4.995.002.002.26.41a.5.5 0 0 0 .886-.083l6-15Zm-1.833 1.89L6.637 10.07l-.215-.338a.5.5 0 0 0-.154-.154l-.338-.215 7.494-7.494 1.178-.471-.47 1.178Z" />
                        </svg>
                    </a>
                    <a href="" class="text-decoration-none text-dark me-3">
                        <!-- Post -->
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                            class="bi bi-plus-square" viewBox="0 0 16 16">
                            <path
                                d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                            <path
                                d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                        </svg>
                    </a>
                    <a href="" class="text-decoration-none text-dark me-3">
                        <!-- Explore -->
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                            class="bi bi-binoculars-fill" viewBox="0 0 16 16">
                            <path
                                d="M4.5 1A1.5 1.5 0 0 0 3 2.5V3h4v-.5A1.5 1.5 0 0 0 5.5 1h-1zM7 4v1h2V4h4v.882a.5.5 0 0 0 .276.447l.895.447A1.5 1.5 0 0 1 15 7.118V13H9v-1.5a.5.5 0 0 1 .146-.354l.854-.853V9.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v.793l.854.853A.5.5 0 0 1 7 11.5V13H1V7.118a1.5 1.5 0 0 1 .83-1.342l.894-.447A.5.5 0 0 0 3 4.882V4h4zM1 14v.5A1.5 1.5 0 0 0 2.5 16h3A1.5 1.5 0 0 0 7 14.5V14H1zm8 0v.5a1.5 1.5 0 0 0 1.5 1.5h3a1.5 1.5 0 0 0 1.5-1.5V14H9zm4-11H9v-.5A1.5 1.5 0 0 1 10.5 1h1A1.5 1.5 0 0 1 13 2.5V3z" />
                        </svg>
                    </a>
                    <a href="" class="text-decoration-none text-dark me-3">
                        <!-- Like -->
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                            class="bi bi-heart-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
                        </svg>
                    </a>
                    <a href="" class="text-decoration-none text-dark me-3">
                        <!-- Profile -->
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>

templates/shared/HeaderRefrence.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/iziToast.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/shared/base.html
{% load static %}
<html lang="fa-ir" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %} {% endblock %}
    </title>
    {% include "shared/HeaderRefrence.html" %}
</head>
<body>
    {% include "shared/Header.html" %}
    {% block styles %}{% endblock %}
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    {% include "shared/FooterRefrence.html" %}
    {% block scripts %}
    {% endblock %}
</body>
</html>